dist: xenial
language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9-dev
install:
- pip install -e .[dev]
script:
- pytest tests --cov=mimid
- black --check .
- mypy mimid
- pylint mimid
after_success:
  coveralls
stages:
- test
- deploy
jobs:
  include:
    - stage: deploy
      script: skip
      python: 3.8
      deploy:
        provider: pypi
        user: khalas
        password:
          secure: QuPM1vc8dBJPmYLHJC7vWRwy51xIw7d08BM3WMXhYwI5nlE4wYrq3bKJYYzIuliML29FTeth1o3MNLtAlFsa88RrcMObRUU6NNeEVi5kVrGulRoJruuieHUmHPviawew/Qn18GZihdikVj9ijJTn0XxijT5dhHprBB9GPDoxBFEVKZpL7YHBXG+I5AWzo/qmD0vNbs849596NIm1+vBZAlOyAYLGYo2WBm8ehHyPOGSN1BL9t3Y75fRvQoFOzyaOQBzC+MU2gO34miEpIBAy2cqKAfgau+DUnQXWEn5ig16Gx6rOkHO3eh7hjCTzZ1857+HCkQ32ds8cVdAGPHorMa4iuDEmGNUk8Y1HeES1ZyiSeaoi4wPRMlgbW+pp5U/rEvOtsFM33ZRTwv2GnuHeneY6GDmscLhXpwy+jgKf3ADTU7UefQKrOT6dSLqqjRNWCH5kkj8EDQfuDnXtYZQ0otCYZA9Bis25+pZdYh9iT66uLPHGJ3fUuDpE0/oMlITOtOzCXfMW4E2IxVM8y7et9ZxugRDjrJYcni5sR5McEHfRluQFxUGwz0QO8hGrsBxOzu7udjX3aaHoonyQzVrstlWfvCa0sn4/PIQ27SQImWZ2pzfKoxup8F6pNUHe0W5/NieNAqUkf9lGEA7mjy+svMjanro2J91T+DtXpCdw4JI=
        on:
          tags: true
        distributions: "sdist bdist_wheel"
